# ./tasks/etc_hosts.yml
---

- name: etc_hosts | copy /etc/hosts
  copy:
    src: /mylab/config/etc_hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: "'etc_hosts' in mylab_node_entities"
