# ./tasks/timezone.yml
---

- name: timezone | set timezone Europe/Berlin (hard coded)
  timezone:
    name: Europe/Berlin
    #notify:
    #- restart crond
  when: "'timezone' in mylab_node_entities"
